// Code generated by "stringer -type=SoftBreakBehavior -output=html_string.go"; DO NOT EDIT.

package commonmark

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SoftBreakPreserve-0]
	_ = x[SoftBreakSpace-1]
	_ = x[SoftBreakHarden-2]
}

const _SoftBreakBehavior_name = "SoftBreakPreserveSoftBreakSpaceSoftBreakHarden"

var _SoftBreakBehavior_index = [...]uint8{0, 17, 31, 46}

func (i SoftBreakBehavior) String() string {
	if i < 0 || i >= SoftBreakBehavior(len(_SoftBreakBehavior_index)-1) {
		return "SoftBreakBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SoftBreakBehavior_name[_SoftBreakBehavior_index[i]:_SoftBreakBehavior_index[i+1]]
}
