name: Test
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  nix:
    name: go test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        run: nix develop --command go test -mod=readonly -race ./...
  windows:
    name: go test (Windows)
    runs-on: windows-2022
    steps:
      - name: Install Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version: "1.20.2"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test -mod=readonly -race ./...
